- hosts: localhost
  tasks:
    - name: Printing the Storage credentials 
      debug:
         msg: "{{ storage_system_ip }} : {{ storage_system_username }} : {{ volume_name }} "

    - name: Delete Volume "{{ volume_name }}"
      hpe3par_volume:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=absent
        volume_name="{{ volume_name }}"
