- hosts: localhost
  tasks:

  - name: Create Volume "{{ volume_name }}"
    hpe3par_volume:
       storage_system_ip: "{{ storage_system_ip }}"
       storage_system_username: "{{ storage_system_username }}"
       storage_system_password: "{{ storage_system_password }}"
       state: present
       volume_name: "{{ volume_name }}"
       cpg: "{{ cpg }}"
       size: "{{ size }}"
       size_unit: "{{ size_unit }}"
       snap_cpg:  "{{ cpg }}"

  - name: remote copy group status
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_password: "{{ storage_system_password }}"
      storage_system_username: "{{ storage_system_username }}"
      state: remote_copy_status
      remote_copy_group_name: "{{ rcopy_group_name }}"
    register: result

  - name: Add volume to remote copy group
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_password: "{{ storage_system_password }}"
      storage_system_username: "{{ storage_system_username }}"
      state: add_volume
      remote_copy_group_name: "{{ rcopy_group_name }}"
      volume_name: "{{ volume_name }}"
      volume_auto_creation: True
      admit_volume_targets:
      - target_name: "{{ target_name }}"
        sec_volume_name: "{{ volume_name }}"
