- hosts: localhost
  tasks:

  - name: remote copy group status
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_password: "{{ storage_system_password }}"
      storage_system_username: "{{ storage_system_username }}"
      state: remote_copy_status
      remote_copy_group_name: "{{ rcopy_group_name }}"
    register: result

  - name: remove volume to remote copy group
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_password: "{{ storage_system_password }}"
      storage_system_username: "{{ storage_system_username }}"
      state: remove_volume
      remote_copy_group_name: "{{ rcopy_group_name }}"
      volume_name: "{{ volume_name }}"
      keep_snap: False
      remove_secondary_volume: True

  - name: Delete Volume "{{ volume_name }}"
    hpe3par_volume:
       storage_system_ip: "{{ storage_system_ip }}"
       storage_system_username: "{{ storage_system_username }}"
       storage_system_password: "{{ storage_system_password }}"
       state: absent
       volume_name: "{{ volume_name }}"

