- hosts: localhost
  tasks:
  - name: remote copy group status
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_password: "{{ storage_system_password }}"
      storage_system_username: "{{ storage_system_username }}"
      state: remote_copy_status
      remote_copy_group_name: "{{ rcopy_group_name }}"
    register: result

  - name: Stop remote copy group 
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_password: "{{ storage_system_password }}"
      storage_system_username: "{{ storage_system_username }}"
      state: stop
      remote_copy_group_name: "{{ rcopy_group_name }}"

  - name: remote copy group status
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_password: "{{ storage_system_password }}"
      storage_system_username: "{{ storage_system_username }}"
      state: remote_copy_status
      remote_copy_group_name: "{{ rcopy_group_name }}"
    register: result

  - name: remove volume to remote copy group
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_password: "{{ storage_system_password }}"
      storage_system_username: "{{ storage_system_username }}"
      state: remove_volume
      remote_copy_group_name: "{{ rcopy_group_name }}"
      volume_name: "{{ volume_name }}"
      remove_secondary_volume: True
      admit_volume_targets:
      - target_name: "{{ target_name }}"
        sec_volume_name: "{{ volume_name }}"
        

  - name: Remove Remote Copy Group "{{ rcopy_group_name }}"
    hpe3par_remote_copy:
      storage_system_ip: "{{ storage_system_ip }}"
      storage_system_password: "{{ storage_system_password }}"
      storage_system_username: "{{ storage_system_username }}"
      state: absent
      remote_copy_group_name: "{{ rcopy_group_name }}"
      local_user_cpg: "{{ cpg }}"
      local_snap_cpg: "{{ cpg }}"
      remove_secondary_volume: "true"
      remote_copy_targets:
      - target_name: "{{ target_name }}"
        target_mode: sync
        user_cpg: "{{ target_cpg }}"
        snap_cpg:  "{{ target_cpg }}"

  - name: Delete Volume "{{ volume_name }}"
    hpe3par_volume:
       storage_system_ip: "{{ storage_system_ip }}"
       storage_system_username: "{{ storage_system_username }}"
       storage_system_password: "{{ storage_system_password }}"
       state: absent
       volume_name: "{{ volume_name }}"
       cpg: "{{ cpg }}"
       size: "{{ size }}"
       size_unit: "{{ size_unit }}"
       snap_cpg:  "{{ cpg }}"

