- hosts: localhost
  tasks:
    - name: Printing the Storage credentials
      debug:
         msg: "{{ storage_system_ip }} : {{ storage_system_username }}"

    - name: Printing the Storage Volume details
      debug:
         msg: "{{ volume_name }} : {{ cpg }} : {{ size }} : {{ size_unit }} : {{ host_name }}"

    - name: Create Volume "{{ volume_name }}"
      hpe3par_volume:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=present
        volume_name="{{ volume_name }}"
        cpg="{{ cpg }}"
        size="{{ size }}"
        size_unit="{{ size_unit }}"

    - name: Create VLUN
      hpe3par_vlun:
        storage_system_ip="{{ storage_system_ip }}"
        storage_system_username="{{ storage_system_username }}"
        storage_system_password="{{ storage_system_password }}"
        state=export_volume_to_host
        volume_name="{{ volume_name }}"
        host_name="{{ host_name }}"
        autolun=True
